# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: courses_development

test:
  <<: *default
  database: courses_test

production:
  <<: *default
  database: courses_production
  username: rails
  password: M5glzzpMlQ
